version: '3.8'
services:
  python:
    build: ../../python
    volumes:
      - ../../python:/app
    env_file:
      - ../../python/.env
    working_dir: /app
    command: bash
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codexapp
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
