name: CI

on:
  push:
  pull_request:

# Cancel previous runs for the same branch/PR to save compute resources
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Main CI job that runs all checks
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup pnpm (version pinning)
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Ensure pnpm is in PATH
        run: pnpm --version

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          echo "Dependencies installed successfully"

      - name: TypeScript compilation check
        run: |
          echo "Checking TypeScript compilation..."
          npx tsc --noEmit
          echo "TypeScript compilation check passed"

      - name: Lint code and documentation
        run: |
          echo "Running linting checks..."
          pnpm lint
          echo "Linting checks passed"

      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          pnpm test:unit
          echo "Unit tests passed"

      - name: Run integration tests
        run: |
          echo "Running integration tests..."
          QT_ENV=mock pnpm test:integration
          echo "Integration tests passed"

      - name: Check code coverage thresholds
        run: |
          echo "Checking code coverage thresholds..."
          pnpm coverage
          echo "Coverage thresholds met"
